# Generated by Django 5.1.4 on 2026-07-13 21:44

import crisapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crisapp', '0002_contactmessage_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del cliente/proyecto', max_length=100)),
                ('dominio', models.CharField(help_text='Ej: rentasruiz.com', max_length=100)),
                ('url', models.URLField(help_text='Enlace completo al sitio, ej: https://rentasruiz.com')),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(choices=[('hospedaje', 'Hospedaje y Reservaciones'), ('bienes-raices', 'Bienes Raíces'), ('restaurantes', 'Restaurantes y Pedidos'), ('tiendas', 'Tiendas en Línea'), ('ong', 'ONG y Fundaciones'), ('arte', 'Arte y Cultura'), ('servicios', 'Servicios Profesionales'), ('comunidades', 'Comunidades e Instituciones')], max_length=20)),
                ('imagen', models.ImageField(upload_to=crisapp.models.proyecto_image_path)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Menor número aparece primero')),
                ('destacado', models.BooleanField(default=False, help_text='Mostrar con mayor prioridad')),
                ('activo', models.BooleanField(default=True, help_text='Desmarcar para ocultar sin borrar')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['orden', '-destacado', '-fecha_creacion'],
            },
        ),
    ]
