# Generated by Django 5.1.4 on 2026-07-13 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crisapp', '0003_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='color_acento',
            field=models.CharField(default='#00d9ff', help_text='Color del borde superior de la tarjeta y del fondo del badge de categoría. Ej: #00d9ff', max_length=7),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='color_texto',
            field=models.CharField(default='#0a0a0a', help_text='Color del texto del badge de categoría (para que se lea bien sobre el color de acento)', max_length=7),
        ),
    ]
