# Generated by Django 5.1.4 on 2026-08-21 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crisapp', '0004_proyecto_color_acento_proyecto_color_texto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=20)),
                ('num_personas', models.PositiveIntegerField(default=1)),
                ('nota', models.TextField(blank=True)),
                ('fecha_confirmacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Confirmación de asistencia',
                'verbose_name_plural': 'Confirmaciones de asistencia',
                'ordering': ['-fecha_confirmacion'],
            },
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='url',
            field=models.URLField(default='https://'),
        ),
    ]
