# Generated by Django 5.1.4 on 2026-08-26 00:49

import crisapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crisapp', '0005_confirmacion_alter_proyecto_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='bandera_pais',
            field=models.ImageField(blank=True, null=True, upload_to=crisapp.models.proyecto_image_path),
        ),
    ]
