# Generated by Django 5.1.4 on 2026-09-18 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crisapp', '0006_proyecto_bandera_pais'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmacionBash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Full name (first & last, needed for potluck assignment)', max_length=150)),
                ('email', models.EmailField(help_text='Se usa para enviarle el email de confirmación al invitado', max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('num_personas', models.PositiveIntegerField(default=1)),
                ('nota', models.TextField(blank=True, help_text='Dietary restrictions or notes')),
                ('fecha_confirmacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'RSVP — End of Summer Bash',
                'verbose_name_plural': 'RSVPs — End of Summer Bash',
                'ordering': ['-fecha_confirmacion'],
            },
        ),
    ]
